import numpy as np

# sin signal
AMPLITUDE = 10
SAMPLE_RATE = 1
OFFSET = np.pi
WAVE_FREQ = 1000
SAMPLE_LENGHT = 44100
SIGNAL_TYPE_NAME_SIN = 'sin_'

# triangal signal
SIGNAL_TYPE_NAME_TR = 'tr_'
SIGNAL_TYPE_TR = 0.5
WAVE_FREQ_TR = 200
SAMPLE_LENGHT_TR = 44100


# sawtooth signal
SIGNAL_TYPE_NAME_ST = 'st_'
SIGNAL_TYPE_ST = 1
WAVE_FREQ_ST = 100
SAMPLE_LENGHT_ST = 44100

# noise
SIGNAL_TYPE_NAME_NOISE = 'noise_'
SAMPLE_LENGHT_NOISE = 44100
MIN_VALUE = 0
MAX_VALUE = 0.9
AMPLITUDE_NOISE = 20

# diffrent duty
SIGNAL_TYPE_NAME_DUTY = 'duty_'
SAMPLE_LENGHT_DUTY = 44100
OFFSET_DUTY = 0
WAVE_FREQ_DUTY = 300

#square signal
AMPLITUDE_SQ = 20
SIGNAL_TYPE_NAME_SQUARE = 'sq_'
SAMPLE_LENGHT_SQUARE = 44100
WAVE_FREQ_SQ = 100

# directory for signals
DIR = 'signals/'